### ISSUE TITLE
Custom API JSON example

### ISSUE THREAD

**Issue by alexrabin** [levin-riegner/app_versioning#10]
I am not seeing anywhere what the json response for a custom api is supposed to be.

**Comment by Alqueraf** [comment]
Hi @alexrabin, you can see the json response modeled in the [ApiVersioning](../blob/master/lib/src/api/model/api_versioning.dart) class and its `fromJson` method.
The expected format is:
```
{
"minimumIosVersion": "0.0.0",
"minimumAndroidVersion": "0.0.0"
}
```

If you'd like to use a different response format, you can implement your own [MinimumVersioningService](../blob/master/lib/src/service/minimum_versioning_service.dart) using the [DefaultApiVersioningService](../blob/master/lib/src/api/service/default_api_versioning_service.dart) as an example.

**Comment by alexrabin** [comment]
Thank you!
